[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# <----- lp -------->
# classification
[[example]]
name="ml_classification_cros"
path="examples/ml/classification/cros.rs"
[[example]]
name="ml_classification_linear_simple"
path="examples/ml/classification/linear_simple.rs"
[[example]]
name="ml_classification_linear_multiple"
path="examples/ml/classification/linear_multiple.rs"
[[example]]
name="ml_classification_xor"
path="examples/ml/classification/xor.rs"

# resgression
[[example]]
name="ml_regression_cros"
path="examples/ml/regression/cros.rs"
[[example]]
name="ml_regression_linear_simple"
path="examples/ml/regression/linear_simple.rs"
[[example]]
name="ml_regression_linear_multiple"
path="examples/ml/regression/linear_multiple.rs"
[[example]]
name="ml_regression_xor"
path="examples/ml/regression/xor.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.4"
