[package]
name = "mylib"
version = "0.1.0"
edition = "2021"
authors = ["YAHIA ABDCHAFEE Adam", "Théo", "Charbel"]
description = "liner model / multilayer preceptron / radical basis function network / support vecteur machine"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yahia-adam/mylib"
keywords = ["lib", "ai", "machine learning"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
