[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["cdylib"]

[[example]]
name="celsius_to_fahrenheit"
path="examples/liner_model/celsius_to_fahrenheit.rs"

# <----- mlp classification -------->
[[example]]
name="clf_cross"
path="examples/multilayer_perceptron/classification/cross.rs"
[[example]]
name="clf_xor"
path="examples/multilayer_perceptron/classification/xor.rs"
[[example]]
name="clf_linear_multiple"
path="examples/multilayer_perceptron/classification/linear_multiple.rs"
[[example]]
name="clf_linear_simple"
path="examples/multilayer_perceptron/classification/linear_simple.rs"
[[example]]
name="clf_multi_cross"
path="examples/multilayer_perceptron/classification/multi_cross.rs"
[[example]]
name="clf_multi_linear_3classes"
path="examples/multilayer_perceptron/classification/multi_linear_3classes.rs"

# <----- mlp regression -------->
[[example]]
name="regr_linear_simple_3d"
path="examples/multilayer_perceptron/regression/linear_simple_3d.rs"
[[example]]
name="regr_linear_simple"
path="examples/multilayer_perceptron/regression/linear_simple.rs"
[[example]]
name="regr_linear_tricky_3d"
path="examples/multilayer_perceptron/regression/linear_tricky_3d.rs"
[[example]]
name="regr_no_linear_simple_2d"
path="examples/multilayer_perceptron/regression/no_linear_simple_2d.rs"
[[example]]
name="regr_no_linear_simple_3d"
path="examples/multilayer_perceptron/regression/no_linear_simple_3d.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.4"
